import Head from 'next/head'
import * as React from "react"
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import firebase from "firebase/compat/app"
import "firebase/compat/database"
import {Firebase} from "../src/firebase";

export default function Home() {

    type Estados = "limpo" | "sujo" | "ocupado";

    interface Banco {
        nome: string,
        estado: Estados
    }

    const options = ["limpo", "sujo", "ocupado"];

    const [salas, setSalas] =
        React.useState<Array<Banco>>([])

    const transformObjectInArray = (obj) => {
        let arr = []
        for (let key in obj)
            arr.push(obj[key])
        return arr;
    }

    React.useEffect(() => {
        // setToDatabase(Firebase).then(() => alert("finalizado"));
        Firebase.database().ref().child("/salas").on("value", (snap) => {
            if (snap.exists()) {
                setSalas(transformObjectInArray(snap.val()))
            }
        })
    }, []);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <table>
                <thead>
                <th>Sala</th>
                <th>Estado</th>
                </thead>
                <tbody>
                {salas.map(sala => (<tr key={sala.nome} >
                    <td style={{borderBottom: "1px solid #F0F0F0", paddingBottom: 5}}>{sala.nome}</td>
                    <td style={{paddingBottom: 5, borderBottom: "1px solid #F0F0F0", }}>
                        <form>
                            <select
                                style={{backgroundColor:
                                        sala.estado === "sujo" ? "red" :
                                            (sala.estado === "ocupado" ? "yellow" : "green"),
                                        padding: "5px 20px",
                                        borderRadius: "3px",
                                }}
                                onChange={e => {
                                const value = e.target.value;
                                Firebase
                                    .database()
                                    .ref("/salas/"+sala.nome)
                                    .update({estado: value})
                            }}>
                                {
                                    options
                                        .map((option, i) =>
                                            (<option
                                                selected={option === sala.estado}
                                                key={i}>
                                                {option}
                                            </option>))
                                }
                            </select>
                        </form>
                    </td>
                </tr>))}
                </tbody>
            </table>
        </div>
    )
}
